version: "3"

services:
  web:
    build: .
    container_name: reservoir-prediction
    volumes:
      - .:/code
    ports:
      - "5000:81"
    environment:
      - ENABLE_METRICS=true
